name: holly_palm_case
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  carousel_slider: ^5.0.0
  html: ^0.15.5
  bot_toast: ^4.0.3


  cupertino_icons: ^1.0.8
  graphql_flutter: ^5.2.0-beta.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
